apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-api.fullname" . }}
  labels:
    {{- include "helm-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if not (empty .Values.service.clusterIP) }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{end}}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "helm-api.selectorLabels" . | nindent 4 }}
