persistence:
  deleteEnabled: true

service:
  port: 80

ingress:
  enabled: true
  path: /
  annotations:
    nginx.org/mergeable-ingress-type: "minion"
    nginx.org/client-max-body-size: 0
  hosts: [docker-registry.com]

storage: s3

secrets:
  s3:
    accessKey: "AKIAIOSFODNN7EXAMPLE"
    secretKey: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"

s3:
  region: "us-west-1"
  regionEndpoint: http://10.109.104.90
  secure: true
  bucket: docker-registry
