# Default values for polling_server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

docker_pipelines:
  - name: "cicd_test"
    github_url: "https://github.com/nnt1054/cicd_test.git"
    events_url: "https://api.github.com/repos/nnt1054/cicd_test/events"
    registry_url: "docker-registry.com:80"
  - name: "cicd_test2"
    github_url: "https://github.com/nnt1054/cicd_test.git"
    events_url: "https://api.github.com/repos/nnt1054/cicd_test/events"
    registry_url: "docker-registry.com:80"

helm_pipelines:
  - helm_repo_url: "http://docker-registry.com/helm-repo/api/charts"
    charts:
      - name: "testchart"
        latest_version: ""
      - name: "testchart2"
        latest_version: ""
  # - helm_repo_url: "http://docker-registry.com/helm-repo/api/charts"
  #   charts:
  #     - name: "testchart"
  #       latest_version: ""
  #     - name: "testchart2"
  #       latest_version: ""

replicaCount: 1

image:
  repository: nnt1054/polling-server
  tag: 0.0.1
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  clusterIP: 10.108.223.184
  port: 80

ingress:
  enabled: true
  annotations:
    nginx.org/mergeable-ingress-type: "minion"
    nginx.org/rewrites: "serviceName=polling-server rewrite=/"
  hosts:
    - host: docker-registry.com
      paths: 
        - "/polling-server/"
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
